"""empty message

Revision ID: 6d4b87e0ad9f
Revises: 5a1942b46167
Create Date: 2020-05-28 11:27:41.468472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4b87e0ad9f'
down_revision = '5a1942b46167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('goodsID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('word_description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('goodsID')
    )
    op.create_table('shipping_address',
    sa.Column('shipping_addressID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=10), nullable=False),
    sa.Column('area', sa.String(length=10), nullable=False),
    sa.Column('street', sa.String(length=10), nullable=False),
    sa.Column('details', sa.String(length=50), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipping_addressID')
    )
    op.create_table('shopping_cart',
    sa.Column('shopping_cartID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods', sa.JSON(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shopping_cartID')
    )
    op.create_table('shopping_bill',
    sa.Column('shopping_billID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('shipping_addressID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_addressID'], ['shipping_address.shipping_addressID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shopping_billID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_bill')
    op.drop_table('shopping_cart')
    op.drop_table('shipping_address')
    op.drop_table('goods')
    # ### end Alembic commands ###
