"""empty message

Revision ID: 413ae3e5d8c6
Revises: 6d4b87e0ad9f
Create Date: 2020-05-28 22:39:34.225046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413ae3e5d8c6'
down_revision = '6d4b87e0ad9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('image', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'image')
    # ### end Alembic commands ###
