"""empty message

Revision ID: dce4b9dc021d
Revises: 79c0942cb32b
Create Date: 2020-06-03 23:39:30.551356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dce4b9dc021d'
down_revision = '79c0942cb32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_bill', sa.Column('shipping_address', sa.String(length=100), nullable=False))
    op.drop_constraint('shopping_bill_ibfk_1', 'shopping_bill', type_='foreignkey')
    op.drop_column('shopping_bill', 'shipping_addressID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_bill', sa.Column('shipping_addressID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('shopping_bill_ibfk_1', 'shopping_bill', 'shipping_address', ['shipping_addressID'], ['shipping_addressID'])
    op.drop_column('shopping_bill', 'shipping_address')
    # ### end Alembic commands ###
